language: node_js
node_js:
  - "8.5.0"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: "NODE_ENV=test ./node_modules/karma/bin/karma start ./karma.conf.js --browsers Chrome --single-run --no-auto-watch --capture-timeout 6000000"
