name: 'Recharts React Smooth'

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
 smooth-job:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '14'

  - name: Installing deps
    run: npm install

  - name: Testing & Linting
    run: |
      npm run lint
      npm run test

  - name: Building packages
    run: npm run build